### ISSUE TITLE
Repeat notification.

### ISSUE THREAD

**Issue by PandCall** [Looking4Cache/node-red-contrib-remote#12]
Hello Thorsten,
I just discovered your NODE and I'm testing it.
Everything seems to work except that it only sends the notification once.
I would like to receive a notification each time a PAYLOAD changes state.
Is it a configuration error or is it a variable to change in the configuration files or a limitation?
Best regards

**Comment by Looking4Cache** [comment]
Hi,

in my code there is no check for the same notification data to "do not send" a notification. Normally each time a message received by the notification node, a notification should be forwarded the the phone(s). The only limit is a maximum of 100 notifications per notification node per hour.

Can you check your Node-RED logs? When a notification send runs on a error, it's logged out. When you set the log level of Node-RED to debug, every notification send to my servers will be logged too.

Greetings,
Thorsten

**Comment by PandCall** [comment]
Thanks for your quick response.
I don't know why, my tests this morning are working.
I have just one node that returns an error

05/08/2022 10:40:49node: a1d83456d344f3b1
msg.payload: number
7.275
05/08/2022 10:40:49node: d4387042ecf37164
msg: string [44]
"The message exceeded 3600 bytes. Can't send."
05/08/2022 10:40:49node: debug 4
msg.payload : number
7.275

I'll redo all  notifications to make sure it's not an myself error
Regards

Working environment.
Raspberry Pi3
Node-Red 3.01
Local network access only, and for outside private VPN connection.
But for the moment, all tests are on local network only.

**Comment by Looking4Cache** [comment]
The 3600 bytes error is a check where the complete payload that will be send to the Google Cloud Messaging Network is calculated. This payload can't be more than 3600 bytes, as it is a limitation of Google/Apple. Maybe if you send long texts, you should crop them first.

**Comment by PandCall** [comment]
Thorsten,
The problem is probably related to this (attachement)

![remote-notification](https://user-images.githubusercontent.com/33251023/183305774-97874603-ac9e-4a98-854c-b68143a37a35.jpg)

You confirm that the application (android) is limited in number of sendings per day and is not totally free?

Two points to confirm
My initial problem, I did not receive everything, related to the purchase limitation?
The second problem about the size of the message (more than 3600 bytes), is it related to your purchase message?

**Comment by Looking4Cache** [comment]
Remote-RED is not free. It's an application and service that have to been payed by InApp purchases. This is also written directly in the app description on the PlayStore. More infos about that here: https://www.remote-red.com/en/pricing/

With the InApp purchase there are only technical limits on the Notifications: You can not send more than 100 notifications per notification node per hour and you can't send notifications with more than 3600 bytes payload.

After installation of Remote-RED there are some days you don't need the InApp purchases to test if it suits for you.

_The second problem about the size of the message (more than 3600 bytes), is it related to your purchase message?_
The 3600 bytes is a restriction of Google.

_What is this IP address 173.212.245.41:443 used by the NODE?_
This is one of my five servers used for proxy remote connections and sending notifications.

_Probably because this IP address is located in Germany._
Yes, this is one of two servers in Germany. There are also a server in the USA and a server in Singapur is coming in the next release.

**Comment by PandCall** [comment]
Thank you Thorsten,
I am not criticizing that I have to pay for my product, it is normal when a product requires a lot of work and is used professionally.
I think that in the terms of use you should detail all these restrictions. Better explain the use without license.
And the calls to external infrastructure should be indicated, because if like me it is for LAN use only, and I see traffic on external IP, I will block systematically, and this may cause problems, look why it does not work anymore.
Nice job and in fact, I had no problem, just not all the information to understand.
Best Regards
