### ISSUE TITLE
Slow to load up

### ISSUE THREAD

**Issue by PaisBruno** [Looking4Cache/node-red-contrib-remote#4]
Hi there,

I find that the connection takes a while to load up when on an external network. I live in Australia and chose the USA server.
Any idea on how to improve it? Can you change me to the Europe server to see if it loads faster?
Thank you.
Cheers,
b.
P.S.: I am looking into starting a small business to automate and remote control pumps and other gear for the farmers in my region. I'm looking for the best way to deploy a remote access to the devices with node-red that can be easily deployed by sending a link or creating a user on the app so the prospective farmer can download it without having to go through the google store. Would this be something your app could have the ability to do in future versions? Would be happy to pay for this different app instances if I choose to go down this path. Just want to be able to offer a all in one package instead of having to deploy different software for the prospective customers.

**Comment by Looking4Cache** [comment]
Hi,

to test the speed over the EU Server you can just add a second remote access node with a second config node. Give it another name that you know which you have to select in the app. The app can handle several instances at the same time.

But I think it will also be slow. The latency to the server doubles as it is a proxy. So it is the time from your mobile to the server and from the server to your Node-RED instance.

About the "one link": One link is not possible. The user must install the app through an App Store, of course it is possible to open the App Store directly with the correct app. But the installation must go through the App Store. After that it can be possible to connect the Remote-RED Instance through a link. So that it is not needed to connect through a QR Code, instead it will be possible to just click a link to connect the app. I already included that in the Apps and only have to make that link visible inside the config node.

Best regards, Thorsten
